[workspace]
authors = ["Stephen Harding <stephen.harding@epcpower.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly"]
name = "mojo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=26.2.0.dev2026020105,<27"
pillow = ">=12.1.0,<13"
pygame = ">=2.6.1,<3"
numpy = ">=2.4.1,<3"
mpmath = ">=1.3.0,<2"
